name: RFC action

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  rfc-action:
    name: Handle an RFC-related command
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rfc') }}
    runs-on: ubuntu-latest
    steps:
      - uses: paritytech/rfc-action@be7c934ade5bfce5eae889db3d6a286560431333 # v0.0.3
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
