name: RFC action

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  rfc-action:
    name: Handle an RFC-related command
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rfc') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.RFC_BOT_APP_ID }}
          private_key: ${{ secrets.RFC_BOT_PRIVATE_KEY }}
      - uses: paritytech/rfc-action@c673cf6776a2f266c7d8cbb29bc2159bea2cdd78 # v0.0.6
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
